// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2XiKYo6S9gpGc9cyGbvWkvDIEoBz889A',
    appId: '1:1066697489477:web:32dbb6bb659fedd55ff72c',
    messagingSenderId: '1066697489477',
    projectId: 'yakinhalal-863b3',
    authDomain: 'yakinhalal-863b3.firebaseapp.com',
    storageBucket: 'yakinhalal-863b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBftAPp0lJi6EHsvO3cwIeCyfscxbh-maQ',
    appId: '1:1066697489477:android:c724b4688559338b5ff72c',
    messagingSenderId: '1066697489477',
    projectId: 'yakinhalal-863b3',
    storageBucket: 'yakinhalal-863b3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2XiKYo6S9gpGc9cyGbvWkvDIEoBz889A',
    appId: '1:1066697489477:web:2007f37188780bac5ff72c',
    messagingSenderId: '1066697489477',
    projectId: 'yakinhalal-863b3',
    authDomain: 'yakinhalal-863b3.firebaseapp.com',
    storageBucket: 'yakinhalal-863b3.firebasestorage.app',
  );
}
